@echo off
echo Starting HR Payroll Backend Server...
echo Unsetting DATABASE_URL to use .env configuration...
set DATABASE_URL=
echo Starting server on http://localhost:8000...
.\venv\Scripts\python.exe -m uvicorn app.main:app --reload
