// Icon mappings from lucide-react to react-icons
import {
  MdPerson as User,
  MdNotifications as Bell,
  MdClose as X,
  MdAdd as Plus,
  MdSearch as Search,
  MdEdit as Edit,
  MdDelete as Trash2,
  MdLocationOn as MapPin,
  MdBusiness as Building2,
  MdEdit as Edit2,
  MdFileDownload as Download,
  MdMail as Mail,
  MdSend as Send,
  MdCheckCircle as CheckCircle,
  MdAccessTime as Clock,
  MdWarning as AlertCircle,
  MdDescription as FileText,
  MdGroup as Users,
  MdPhone as Phone,
  MdCreditCard as CreditCard,
  MdSave as Save,
  MdCalendarToday as Calendar,
  MdAttachMoney as DollarSign,
  MdTrendingUp as TrendingUp,
  MdCloudUpload as Upload,
  MdSync as RefreshCw,
  MdCheckCircle as CheckCircle2,
  MdApartment as Building,
  MdFilterList as Filter,
  MdArrowBack as ArrowLeft,
} from 'react-icons/md';

export {
  User,
  Bell,
  X,
  Plus,
  Search,
  Edit,
  Trash2,
  MapPin,
  Building2,
  Edit2,
  Download,
  Mail,
  Send,
  CheckCircle,
  Clock,
  AlertCircle,
  FileText,
  Users,
  Calendar,
  DollarSign,
  TrendingUp,
  Upload,
  RefreshCw,
  CheckCircle2,
  Building,
  Filter,
  Phone,
  CreditCard,
  Save,
  ArrowLeft
};